---
apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: csi-s3-system
stringData:
  accessKeyID: <PUT_YOUR_BASE64_PASSWORD_HERE>
  secretAccessKey: <PUT_YOUR_BASE64_PASSWORD_HERE>
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://minio-service.kubeflow:9000
  # If not on S3, set it to ""
  region: ""
